name: single_cell
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.9
  - r-base=4.2
  - r-essentials
  - r-devtools
  - r-tidyverse
  - r-dplyr
  - r-ggplot2
  - r-patchwork
  - r-tibble
  - r-stringr
  - r-readr
  - r-data.table
  - r-matrix
  - r-rcolorbrewer
  - r-pheatmap
  - r-ggpubr
  - r-survival
  - r-survminer
  - r-glmnet
  - r-timeroc
  - r-geoquery
  - r-limma
  - r-json
  - r-rjson
  - r-future
  - r-hdf5r
  - bioconductor-org.mm.eg.db
  - bioconductor-clusterprofiler
  - bioconductor-enrichplot
  - bioconductor-msigdbr
  - bioconductor-singleR
  - bioconductor-slingshot
  - bioconductor-monocle
  - bioconductor-gsva
  - bioconductor-limma
  - bioconductor-aucell
  - bioconductor-scenic
  - r-harmony
  - r-seurat
  - r-seuratdisk
  - r-copykat
  - r-cellchat
  - r-glmgampoi
  - r-doubletfinder
  - pip
  - pip:
    - anndata
    - scanpy
    - loompy
